# Generated by Django 3.0.4 on 2020-03-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViralScreener', '0003_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
