# Generated by Django 3.0.4 on 2020-03-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ViralScreener', '0005_employeescreeningresponses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeescreeningresponses',
            old_name='author',
            new_name='Screener',
        ),
    ]
