# Generated by Django 3.0.4 on 2020-03-26 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ViralScreener', '0006_auto_20200325_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeescreeningresponses',
            name='Employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ViralScreener.Employee'),
            preserve_default=False,
        ),
    ]
