# Generated by Django 3.0.4 on 2020-03-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViralScreener', '0007_employeescreeningresponses_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeescreeningresponses',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeescreeningresponses',
            name='Symptoms',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], default=None, max_length=200),
            preserve_default=False,
        ),
    ]
