# Generated by Django 3.0.4 on 2020-03-26 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ViralScreener', '0009_auto_20200326_0339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeScreeningResponses',
            new_name='EmployeeScreeningResponse',
        ),
        migrations.CreateModel(
            name='VisitorScreeningResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptoms', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], max_length=200)),
                ('Contact', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], max_length=200)),
                ('DateTime', models.DateTimeField()),
                ('Screener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViralScreener.Visitor')),
            ],
        ),
    ]
