# Generated by Django 3.0.4 on 2020-03-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViralScreener', '0010_auto_20200326_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeescreeningresponse',
            name='ElevatedTemp',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorscreeningresponse',
            name='ElevatedTemp',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], default=None, max_length=200),
            preserve_default=False,
        ),
    ]
